server:
  url: localhost
  port: 7777

spring:
  datasource:
    url: jdbc:cubrid:rmsoft3.iptime.org:34000:rfid:::?charset=UTF-8
    driver-class-name: cubrid.jdbc.driver.CUBRIDDriver
    username: rfid
    password: rfid

  devtools.livereload.enabled: true

  freemarker.cache: false

  thymeleaf.cache: false